chore:
- pr-title:
  - '\bchore\b'

docs:
- pr-title:
  - '\bdocs\b'

feat:
- pr-title:
  - '\bfeat\b'

fix:
- pr-title:
  - '\bfix\b'

refactor:
- pr-title:
  - '\brefactor\b'

remove:
- pr-title:
  - '\bremove\b'

style:
- pr-title:
  - '\bstyle\b'

test:
- pr-title:
  - '\btest\b'
